const STATE={customers:[],vendors:[],items:[],invoices:[],estimates:[],expenses:[],bills:[],config:{bizName:'My Business',gstin:'',address:'',phone:'',email:'',stateCode:'27',currency:'₹',invPrefix:'INV-',invCounter:1,estPrefix:'EST-',estCounter:1}};
const AI={
similarity(a,b){a=(a||'').toLowerCase().trim();b=(b||'').toLowerCase().trim();if(!a||!b)return 0;if(a===b)return 1;const longer=a.length>b.length?a:b;const shorter=a.length>b.length?b:a;if(longer.includes(shorter))return shorter.length/longer.length;const costs=[];for(let i=0;i<=shorter.length;i++){let last=i;for(let j=0;j<=longer.length;j++){if(i===0)costs[j]=j;else if(j===0)costs[j]=i;else{const cur=costs[j];costs[j]=shorter[i-1]===longer[j-1]?last:1+Math.min(last,costs[j-1],costs[j]);last=cur;}}}return 1-costs[longer.length]/longer.length;},
forecast(values,periods=3){const n=values.length;if(n<2)return Array(periods).fill(values[0]||0);let sumX=0,sumY=0,sumXY=0,sumX2=0;for(let i=0;i<n;i++){sumX+=i;sumY+=values[i];sumXY+=i*values[i];sumX2+=i*i;}const slope=(n*sumXY-sumX*sumY)/(n*sumX2-sumX*sumX||1);const intercept=(sumY-slope*sumX)/n;const result=[];for(let i=0;i<periods;i++)result.push(Math.max(0,slope*(n+i)+intercept));return result;},
detectAnomalies(values,threshold=2){if(values.length<3)return[];const mean=values.reduce((a,b)=>a+b,0)/values.length;const variance=values.reduce((s,v)=>s+Math.pow(v-mean,2),0)/values.length;const std=Math.sqrt(variance);if(std===0)return[];return values.map((v,i)=>({index:i,value:v,zScore:(v-mean)/std,isAnomaly:Math.abs((v-mean)/std)>threshold})).filter(x=>x.isAnomaly);},
categorizeExpense(description){const text=(description||'').toLowerCase();const rules={'Rent':['rent','lease','office space','workspace'],'Utilities':['electricity','water','gas bill','internet','broadband','wifi','phone bill','mobile bill'],'Salaries':['salary','salaries','payroll','wages','staff pay'],'Marketing':['ad','ads','marketing','facebook','google ads','instagram','promo','campaign'],'Travel':['travel','flight','train','taxi','uber','ola','cab','hotel','stay'],'Software':['saas','software','subscription','aws','azure','google cloud','notion','slack','zoom'],'Office Supplies':['stationery','paper','pen','printer','ink','cartridge'],'Professional Fees':['lawyer','legal','chartered','ca fee','audit','consultant','advisor'],'Maintenance':['repair','maintenance','service','fix','amc'],'Insurance':['insurance','policy','premium']};for(const[cat,keywords]of Object.entries(rules)){if(keywords.some(k=>text.includes(k)))return{category:cat,confidence:0.9};}return{category:'Other',confidence:0.3};},
predictCustomerValue(customerId,invoices){const custInvoices=invoices.filter(i=>i.customerId===customerId);if(!custInvoices.length)return{avg:0,total:0,count:0};const amounts=custInvoices.map(i=>i.total);const total=amounts.reduce((a,b)=>a+b,0);return{avg:total/amounts.length,total,count:amounts.length,last:amounts[amounts.length-1]};},
churnRisk(thresholdDays=60){const now=Date.now();const risky=[];STATE.customers.forEach(c=>{const custInv=STATE.invoices.filter(i=>i.customerId===c.id);if(!custInv.length)return;const lastDate=new Date(Math.max(...custInv.map(i=>new Date(i.date).getTime())));const days=Math.floor((now-lastDate)/86400000);const totalSpent=custInv.reduce((s,i)=>s+i.total,0);if(days>thresholdDays&&totalSpent>0)risky.push({customer:c,daysSince:days,totalSpent,invoiceCount:custInv.length});});return risky.sort((a,b)=>b.totalSpent-a.totalSpent);},
findDuplicates(){const dupCustomers=[];for(let i=0;i<STATE.customers.length;i++)for(let j=i+1;j<STATE.customers.length;j++){const sim=AI.similarity(STATE.customers[i].name,STATE.customers[j].name);if(sim>0.85)dupCustomers.push({a:STATE.customers[i],b:STATE.customers[j],score:sim});}const dupItems=[];for(let i=0;i<STATE.items.length;i++)for(let j=i+1;j<STATE.items.length;j++){const sim=AI.similarity(STATE.items[i].name,STATE.items[j].name);if(sim>0.85)dupItems.push({a:STATE.items[i],b:STATE.items[j],score:sim});}return{customers:dupCustomers,items:dupItems};},
parseNaturalInvoice(text){if(!text)return null;const t=text.trim();const result={customer:null,items:[],date:null,notes:''};for(const c of STATE.customers){if(t.toLowerCase().includes(c.name.toLowerCase())){result.customer=c;break;}}const itemRegex=/(\d+(?:\.\d+)?)\s*(?:x|×|of|units? of)?\s+([A-Za-z][A-Za-z0-9 _-]{1,40}?)\s*(?:at|@|for|rate)\s*(?:₹|rs\.?|inr|\$)?\s*(\d+(?:\.\d+)?)/gi;let match;while((match=itemRegex.exec(t))!==null){const qty=parseFloat(match[1]);const name=match[2].trim();const rate=parseFloat(match[3]);const foundItem=STATE.items.find(i=>AI.similarity(i.name,name)>0.7);result.items.push({itemId:foundItem?.id||'',name:foundItem?.name||name,qty,rate,gst:foundItem?.gst??18});}const dateRegex=/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})/;const dm=t.match(dateRegex);if(dm){let[,d,m,y]=dm;if(y.length===2)y='20'+y;result.date=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}return result;},
reorderRecommendations(){const recs=[];STATE.items.forEach(it=>{const stock=Number(it.stock)||0;const sold=STATE.invoices.flatMap(i=>i.items||[]).filter(li=>li.itemId===it.id).reduce((s,li)=>s+li.qty,0);const velocity=sold/Math.max(1,STATE.invoices.length?30:1);if(stock<=5&&velocity>0)recs.push({item:it,stock,velocity,suggested:Math.ceil(velocity*30)});});return recs.sort((a,b)=>b.velocity-a.velocity);},
paymentPriorities(){const now=Date.now();const items=[];STATE.invoices.forEach(inv=>{const bal=inv.total-(inv.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0);if(bal<=0)return;const days=Math.floor((now-new Date(inv.date))/86400000);const priority=(bal/1000)+(days/10);items.push({invoice:inv,balance:bal,daysOverdue:days,priority,customerName:inv.customerName});});return items.sort((a,b)=>b.priority-a.priority);}
};
let _db=null;
function idb(){return new Promise((ok,err)=>{const r=indexedDB.open('janaac',1);r.onupgradeneeded=e=>e.target.result.createObjectStore('s');r.onsuccess=e=>ok(e.target.result);r.onerror=e=>err(e.target.error);});}
async function load(){try{_db=await idb();return new Promise(ok=>{const t=_db.transaction('s','readonly');const r=t.objectStore('s').get('main');r.onsuccess=()=>{if(r.result){Object.assign(STATE,r.result);STATE.config={...{bizName:'My Business',gstin:'',address:'',phone:'',email:'',stateCode:'27',currency:'₹',invPrefix:'INV-',invCounter:1,estPrefix:'EST-',estCounter:1},...(r.result.config||{})};}ok();};r.onerror=()=>ok();});}catch{return;}}
async function save(){try{if(!_db)_db=await idb();return new Promise(ok=>{const t=_db.transaction('s','readwrite');t.objectStore('s').put(JSON.parse(JSON.stringify(STATE)),'main');t.oncomplete=()=>ok();t.onerror=()=>ok();});}catch{return;}}
const $=id=>document.getElementById(id);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const nowStr=()=>new Date().toLocaleString();
const money=n=>STATE.config.currency+(Number(n)||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(msg,kind){const t=$('toast');t.textContent=msg;t.className='toast on'+(kind?' '+kind:'');clearTimeout(t._tm);t._tm=setTimeout(()=>t.className='toast',2400);}
function openModal(html){$('modalBox').innerHTML=html;$('modalBg').classList.add('on');}
function closeModal(){$('modalBg').classList.remove('on');$('modalBox').innerHTML='';}
window.closeModal=closeModal;
function computeTax(lines,customerState){const intra=!customerState||!STATE.config.stateCode||customerState===STATE.config.stateCode;let subtotal=0,cgst=0,sgst=0,igst=0;lines.forEach(l=>{const amount=(Number(l.qty)||0)*(Number(l.rate)||0);subtotal+=amount;const tax=amount*(Number(l.gst)||0)/100;if(intra){cgst+=tax/2;sgst+=tax/2;}else igst+=tax;});return{subtotal,cgst,sgst,igst,taxTotal:cgst+sgst+igst,total:subtotal+cgst+sgst+igst};}
function paidAmount(inv){return(inv.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0);}
function balance(inv){return Math.max(0,inv.total-paidAmount(inv));}
function invStatus(inv){const paid=paidAmount(inv);if(paid>=inv.total-0.01)return'paid';if(paid>0)return'partial';return'pending';}
function pillFor(status){const map={paid:'ok',partial:'warn',pending:'err',converted:'ok',open:'info',unpaid:'err',draft:'none'};return`<span class="pill ${map[status]||'none'}">${status}</span>`;}
